### ISSUE TITLE
Modulare, einbettbare & teilbare Grafiken

### ISSUE THREAD

**Issue by chreman** [Forum-Informationsfreiheit/offenewahlen_api#10]
Basis-Visualisierungen
* Karte zu Auszählungs-Stand
* Karte zu aktuellem Ergebnis
* Balkendiagramm zu aktuellem Ergebnis
* Mandate

**Comment by frocentus** [comment]
Die Mandate kommen aber nicht im XML mit, die müssten dann noch selbst berechnet werden?

**Comment by skasberger** [comment]
@frocentus jep, ziemlich sicher.

**Comment by ginseng666** [comment]
ad Mandate ist zu überlegen, wie man sie schnell mit unvollständigen Daten berechnet, da die Regional- und Landeswahlkreise recht lange unvollständig sind (abgesehen von den Wahlkarten). Ev. d'Hondt auf das jeweilige Gesamtergebnis, das kann dann von der "richtigen" Berechnung leicht abweichen - ist aber wohl verschmerzbar, wenns ohnehin um die Darstellung der offiziellen Daten geht (ohne eigene Hochrechnung).

**Comment by frocentus** [comment]
Ich würde fast sagen, wenn man mit der Ungenauigkeit leben kann, dann würde ich die Hare'sche Rechnung der Wahlkreise nehmen. Die Masse der Mandate wird eh über die Landeslisten per Hare'scher Rechnung gemacht, und die ist auch viel leichter zum Implementieren wie d'Hondt.
