### ISSUE TITLE
Tests: Datenauslieferung

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#108]
* [ ] Skalieren die Datenbankabfragen auch unter hoher Last?

postgreSQL

CSV File
* [ ] Beinhaltet CSV Export die korrekten Daten?
* [x] Ist die CSV File über die korrekte URI erreichbar?
* [ ] Stimmt Header von File?
* [ ] Ist die Formatierung (Quote, Seperator) wie gewünscht.

**Comment by chreman** [comment]
könnte dafür mal nen load-test durchführen.

**Comment by skasberger** [comment]
schau dir das mal an, aber solange vom frontend noch nicht die nötigen queries getriggered werden, macht das wenig sinn. am ehesten könntest noch die API testen, was ja im prinzip eh die queries sind. aber werd das irgendwann auf das rest-framework umstellen, hat also auch noch keine wirkliche aussage. mach ma am besten 1-2 wochen vor der wahl.
