### ISSUE TITLE
Normalisieren?

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#116]
Was ist normalisieren einer Website und sollen/müssen wir das machen?

**Comment by 5k9m** [comment]
Im Frontend-Kontext kenne ich es so:
Normalize.css makes browsers render all elements more consistently and in line with modern standards. It precisely targets only the styles that need normalizing.
=> https://necolas.github.io/normalize.css/

Persönlich bin ich eher ein Resetter, aber das ist Geschmacksache.

**Comment by skasberger** [comment]
ok. das reicht mir als Antwort. Hab schon befürchtet, ich hätte da etwas ganz Wichtiges versäumt, was aktuell alle machen.

**Comment by skasberger** [comment]
normalisieren ist nicht zwingend. wir sehen eh mehr, wenn wir mit frontend anfangen.
