### ISSUE TITLE
API: use djangorestframework

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#120]
API mittels Django Restframework ausliefern.

**Comment by skasberger** [comment]
die api endpoints könnte man auch mit "paged" funktion aufsetzen, also dass nur max 100/250 oder 500 ergebnisse pro abfrage retourniert werden, und somit unser server keine probleme bekommt.

**Comment by tobias47n9e** [comment]
Hab hier damit angefangen: https://github.com/OKFNat/offenewahlen-nrw17/pull/204

**Comment by skasberger** [comment]
done. https://github.com/OKFNat/offenewahlen-nrw17/pull/204
