### ISSUE TITLE
Wollen wir ein Ergebnis-Rate-Spiel machen?

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#129]

**Comment by 5k9m** [comment]
In welchem Zeitraum sollte das Rate-Spiel möglich sein?

Finde es zwar ein nettes Gimmick, mehr aber auch nicht. Wenn es in in den Scope passt, dann ja - wenn nicht, dann würde ich es imo weg lassen.

**Comment by skasberger** [comment]
Ich glaube auch, dass wir das zeitlich einfach nicht mehr gut hinbekommen. Idee find ich aber gut, aber eher beim nächsten Mal.
