### ISSUE TITLE
Browser Kompatibilität

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#130]
Wo setzen wir die Grenzen?

**Comment by ximex** [comment]
Vorschlag:
- IE 11
- Edge 14+
- FF 52+
- Chrome 60+
- Opera 47+
- Safari 10+

**Comment by skasberger** [comment]
@ginseng666 kannst du da was von Seiten D3 bzw. Datenvisualisierung sagen?

**Comment by ginseng666** [comment]
das sollte alles funktionieren

**Comment by skasberger** [comment]
done.
