### ISSUE TITLE
Sollen auch Vergleiche zwischen Parteien möglich sein?

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#132]

**Comment by ximex** [comment]
Welche Vergleiche meinst du?

**Comment by skasberger** [comment]
Wir wollen einen Abschnitt machen, wo man zwei Gemeinden, Bezirke oder Bundesländer miteinander vergleichen kann, via Suchformular-Eingabe. Die Frage ist, ob wir auch einen eigenen View für den Vergleich von zwei Parteien dazu geben wollen.

**Comment by skasberger** [comment]
done. wird im style-guide entschieden, aber eher nein.
