### ISSUE TITLE
CI Guideline & Resourcen

### ISSUE THREAD

**Issue by 5k9m** [Forum-Informationsfreiheit/offenewahlen_api#135]
Gibt es eine CI-Guideline sowie alle Resourcen (Logo, Maps, Icons, ...) irgendwo als Download? würde gerne mit ein paar Mock-up Ideen herumspielen, hab aber leider nichts gefunden.

**Comment by skasberger** [comment]
CI Guideline gibts keine. Ich hab da am Anfang mal die beiden Grafiken erstellt, das wars bis dato. :)
Darfst dich da also frei austoben.

Logos findest hier: https://github.com/OKFNat/offenewahlen-at
