### ISSUE TITLE
Https für Domains hinzufügen

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#14]
https://devcenter.heroku.com/articles/automated-certificate-management
https://devcenter.heroku.com/articles/custom-domains

**Comment by skasberger** [comment]
Robert Harm hat Hilfe dabei angeboten.

**Comment by skasberger** [comment]
nicht vergessen, das forwarding von anderen seiten auf https upzudaten: website, etc.

**Comment by ximex** [comment]
Ja das redirect fehlt noch und einige links hier in github sind noch mit http
