### ISSUE TITLE
Social Sharing Funktion entwickeln

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#142]
Sich überlegen, wie jede Darstellung mittels URI eindeutig wiederherstellbar und somit teilbar ist.

Einfliessende Faktoren:
* Datenstand: Zeitstempel des Renderings, der zu dem dann verwendeten Datenstand rückschliessen lässt.
* Auswahl bei Visualisierungen: Welche Daten wurden visuell dargestellt?
* Vorschaubild rendern und bei Aufruf des Bildes ausliefern (oder wie man das auch immer macht, dass ein Bild bei Facebook angezeigt wird).
* es soll einfach sein, eine Grafik zu teilen.

**Comment by 5k9m** [comment]
Die imo einfachste Umsetzung wäre, jene Darstellungen separat auf einer dynamisch generieren Seite darzustellen. Wenn der User eine Darstellung auf der Startseite z.B. auf Facebook teilen will, wird diese Seite verlinkt. Grund: Facebook generiert mit dem [Open Graph protocol](http://ogp.me/) die Darstellung auf Facebook, implementiert via Head-Metadaten; daher sollte das eindeutig sein.

Ein Möglichkeit wäre die Darstellungen dann periodisch als Image zu generieren, z.B. mit [wkhtmltoimage](https://github.com/wkhtmltopdf/wkhtmltopdf). Probleme dabei sehe ich aber vor allem im Facebook-Caching-System. Diese Inhalte lassen sich via [Facebook Debugging Tool](https://developers.facebook.com/tools/debug/) updaten; ob wir das automatisiert via API können, weiß ich leider nicht.

**Comment by skasberger** [comment]
https://github.com/OKFNat/offenewahlen-nrw17/issues/10

**Comment by skasberger** [comment]
Hab hier mal begonnen, die PDF Export Funktion in Django auszuprobieren. https://github.com/skasberger/offenewahlen-nrw17/tree/feature/renderPreviewImage
