### ISSUE TITLE
API: Wahlergebnisse mit Gemeindecode oder Gemeindekennzahl?

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#160]
@ginseng666  soll als key der gemeinde_code oder die gemeinde_kennzahl verwendet werden? es muss dabei beachtet werden, ob bei der Erzeugung des JSON, Daten immer wieder überschrieben werden und so verloren gehen, weil der Key von verschiedenen Gemeinden gleich ist.

**Comment by ginseng666** [comment]
das hängt nur davon ab, ob wir die wiener bezirke eigens differenzieren wollen oder nicht, sonst sind sie identisch

**Comment by skasberger** [comment]
@ginseng666 hat die topojson als keys die GKZ oder den gemeinde-code drinnen?

**Comment by ginseng666** [comment]
die gkz, ist aber egal, da die wiener bezirke ohnehin nicht drinnen sind.

**Comment by frocentus** [comment]
Ich würd schon sehr für den Gemeindecode plädieren, gehören doch die Bezirke Wiens für sich ja schon zu den größten Städten Österreichs :)
