### ISSUE TITLE
Kann eine wahlwerbende Liste aus mehreren Parteien zusammen gesetzt sein?

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#162]
@ginseng666

**Comment by ginseng666** [comment]
naja im grunde schon, man könnte sich vorstellen, dass eine liste parteimitglieder unterschiedlicher parteien (plus vielleicht parteifreie) vereint, usus ist das nicht.

**Comment by skasberger** [comment]
hab da an so manche allianz zwischen kpö, piraten und wandel und dieses mal den jungen grünen gedacht. die zentrale Frage für mich ist: ist das unter der kpö gemeldet, oder kann eine wahlwerbende liste auch unter mehreren parteien gemeldet werden?

**Comment by ginseng666** [comment]
nachdem die parteien formal keine rolle spielen imho nein, es gibt einen zustellungsbevollmächtigten, das wars: http://www.bmi.gv.at/cms/BMI_wahlen/nationalrat/kandidatur.aspx

**Comment by ximex** [comment]
Wahlwerber und Parteien sind 2 verschiedene Dinge nach meinem Verständnis. Theoretisch müsste es sogar möglich sein das eine Partei sagt sie unterstützt 2 Listen.
Meist ist halt einfach: 1 Partei = 1 Liste

**Comment by skasberger** [comment]
Für mich ist die Differenzierung wichtig: was muss bei der Meldung beim BMI angegeben werden. Ob dann im Wahlkampf sich mehrere Parteien für eine Liste aussprechen ist dann ne andere Sache. Aber auf jeden Fall spannend, wie man das in den Daten abbildet. Das faktische oder das rechtliche. :)
