### ISSUE TITLE
Recherchieren, was der Unterschied zwischen Gemeindecode und Gemeindekennzahl ist

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#166]
Die beiden unterscheiden sich nur in Wien. Wien hat eine gesamte Gemeindekennzahl (90001) und jeder einzelne Bezirk hat einen eigenen Gemeindecode (90101 - 92301).

Bsp [Wien](https://de.wikipedia.org/wiki/Wien).

https://de.wikipedia.org/wiki/Amtlicher_Gemeindeschl%C3%BCssel#.C3.96sterreich

@ginseng666 hast du da nähere Infos, woher der Unterschied stammt?

**Comment by frocentus** [comment]
> Das Gemeindeverzeichnis bildet diese Verwaltungsgliederung ab. Es enthält alle 2.100 Gemeinden Österreichs, der Gemeinde ist eine 5-stellige Gemeindekennziffer (GKZ) zugeordnet. Die Vergabe der Gemeindekennziffer obliegt Statistik Austria (Adressregisterverordnung – AdrRegV, BGBl. 218/2005, §1).

> Für statistische Erhebungen bzw. Auswertungen wird ein erweitertes Verzeichnis angeboten. Der Gemeinde ist ein Gemeindecode (GCD) zugeordnet. Mit Ausnahme der Bundeshauptstadt Wien, diese ist nach den 23 Wiener Gemeindebezirken aufgegliedert, ist der Gemeindecode ident mit der Gemeindekennziffer.

Wenn man sich das [XLSX ](http://www.bmi.gv.at/cms/BMI_wahlen/nationalrat/2013/End_Gesamt.aspx)von der BMI Seite ansieht, erkennt man, dass zumindest bei der Nationaratswahl 2013 das BMI mit einer Form des Gemeindecodes arbeitet

GKZ|Gebiet
-------|------------
G90000 | Wien
G90099 | Wahlkarten - W, ungÃ¼ltig nicht zuordenbar
G90100 | Wien  1.,Innere Stadt
G90101 | Innere Stadt
G90199 | Wahlkarten - Wien  1.,Innere Stadt
G90200 | Wien  2.,Leopoldstadt
G90201 | Leopoldstadt
G90299 | Wahlkarten - Wien  2.,Leopoldstadt
G90300 | Wien  3.,Landstraße
G90301 | Landstraße
G90399 | Wahlkarten - Wien  3.,Landstraße
G90400 | Wien  4.,Wieden
G90401 | Wieden
G90499 | Wahlkarten - Wien  4.,Wieden
G90500 | Wien  5.,Margareten

Und im Vergleich die Gemeindecodes inkl. Einwohner von der [Statistik Austria](https://www.statistik.at/wcm/idc/idcplg?IdcService=GET_NATIVE_FILE&RevisionSelectionMethod=LatestReleased&dDocName=103419):

Gemeindcode|OKR|Ortschaft|Einwohner
---------------|-------|----------|--------
90101 | 17223 | Wien 1., Innere Stadt | 16.465
90201 | 17224 | Wien 2., Leopoldstadt | 105.003
90301 | 17225 | Wien 3., LandstraÃŸe | 90.183
90401 | 17226 | Wien 4., Wieden | 33.035
90501 | 17227 | Wien 5., Margareten | 55.356
90601 | 17228 | Wien 6., Mariahilf | 31.865
90701 | 17229 | Wien 7., Neubau | 32.197
