### ISSUE TITLE
config vars in django nutzen

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#17]
entweder eine config.json erstellen oder via [heroku config vars](https://devcenter.heroku.com/articles/getting-started-with-python#define-config-vars).

**Comment by chreman** [comment]
welche config vars genau werden gebraucht?

**Comment by skasberger** [comment]
ne var `url_xml`wo die url zur xml file vom BMI drinnen ist. an sich ein sammel surium aus daten, die nicht online gestellt werden sollen (piwik??).

**Comment by skasberger** [comment]
wird ohne config vars gelöst.
