### ISSUE TITLE
Räumliche Einteilung Wien

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#170]
Was ist genau ein/der

1. Bezirk, 
2. die Gemeinde und 
3. das Bundesland 

bei Wien??

**Comment by frocentus** [comment]
IMHO:
- Bezirk ist "Favoriten, Simmering, usw."
- Die Gemeinde ist Wien, also das gesamte Gebiet
- Das Bundesland ist in dem Fall ident mit der Gemeinde
