### ISSUE TITLE
Kontaktaufnahme Falter

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#174]
mit dem Falter besprechen, ob Sie interesse an Berichterstattung zu OW-AT haben.

Ideen:
* Abdrucken einer Visualisierung nach der Wahl
* Berichten über Open Data, Transparenz und Wahlen davor
* Berichten über ehrenamtliche Arbeit rund um Daten, Visualisierungen und Demokratie
* "Digitale Innovation für alle, statt Datensilos für wenige."

**Comment by ginseng666** [comment]
da rührt sich leider gar nichts seitens falter, leider interessieren sie sich oft für solche sachen erst last minute
