### ISSUE TITLE
Liste mit Gemeindekennzahlen die keine Gemeinden sind sammeln

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#175]
z. B. 
* Wahlkarten
* Bundesländer
* Bezirke
* Regionalwahlkreise

Dies müssen auch in die PollingStation() Tabelle importiert werden.

**Comment by ginseng666** [comment]
du solltest das recht einfach herausfiltern können: wenn die letzten zwei stellen != "00" und != "99" -> gemeinde
