### ISSUE TITLE
Datenformat (Wunsch) - Eine (einfache) SQLite Datei / Archiv etwa nrw17.db

### ISSUE THREAD

**Issue by geraldb** [Forum-Informationsfreiheit/offenewahlen_api#179]
Hallo,
   Als (alternatives) Datenformat wäre der Wunsch eine (einfache) SQLite Datei / Archiv etwa `nrw17.db`. SQLite ist gemeinfrei (public domain), überall verfügbar (Mac, Windows. Linux, etc.), Datenstruktur selbstbeschreibend, und so weiter und so fort.  Mehr Infos zu SQLite etwa <https://sqlite.org/appfileformat.html>.  Dranbleiben. Gruss. Gerald

**Comment by skasberger** [comment]
Danke Gerald, sollte sich machen lassen, vermutlich aber erst nach der NRW17 wenn wir dann die API fertig machen.

**Comment by geraldb** [comment]
Ist nur ein Vorschlag. Wären die Daten in SQLite, dann ist die API (mit GraphQL [1]) auch schon fertig! Etwa mit Ruby ;-) ist das "mappen" von SQL nach GraphQL praktisch (voll)automatich [2]. Riesiger Vorteil von GraphQL - genau wie mit SQL - jeder kann sich seine Abfragen (Queries) selber zusammenstellen. Natürlich schadet es nicht ;-) ein paar Beispielabfragen (Queries) vorher zum einfachen Kopieren zusammenzustellen. Dranbleiben. Gruss.
[1]: http://graphql.org
[2]: http://graphql-ruby.org

**Comment by skasberger** [comment]
Warum hast du das Issue geschlossen?

**Comment by geraldb** [comment]
War nur ein (kleiner) Vorschlag.  Ich mache einen "Winterputz" und schließe alle Tickets die ich mal geöffnet habe.  Danke für die großartige Initiative.  Frohe Weihnachten und Prost 2019! Cheers.
