### ISSUE TITLE
Tests: Daten-Import

### ISSUE THREAD

**Issue by chreman** [Forum-Informationsfreiheit/offenewahlen_api#22]
* outgoing queries from preprocessor
* korrektes schreiben zur db (backend)
* korrektes lesen aus der db (frontend)

**Comment by skasberger** [comment]
@tobias47n9e https://stackoverflow.com/questions/13705328/how-to-run-django-tests-on-heroku

**Comment by skasberger** [comment]
- [ ] Test-Datensätze (XML + TXT) ausarbeiten und online zugänglich machen ([#15](https://github.com/OKFNat/offenewahlen-nrw17/issues/15)).
  - [ ] Ergebnis-Daten importieren und in DB speichern ([#5](https://github.com/OKFNat/offenewahlen-nrw17/issues/5), [#4](https://github.com/OKFNat/offenewahlen-nrw17/issues/4)).
  - [ ] Simulieren 
    - [ ] einer laufenden Wahl 
    - [ ] einer abgeschlossenen Wahl
  - [ ] Basis-Daten importieren und in DB speichern
  - [ ] Variablen-Typen checken: Stimmen nur Integer, etc.

**Comment by skasberger** [comment]
done. teilweise in https://github.com/OKFNat/offenewahlen-nrw17/issues/52 verschoben.
