### ISSUE TITLE
Database creation fails

### ISSUE THREAD

**Issue by fleimgruber** [Forum-Informationsfreiheit/offenewahlen_api#229]
I followed the install instructions and the step

```
python src/manage.py migrate
```
fails with

```
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
```
I had a look and found https://github.com/OKFNat/offenewahlen-nrw17/blob/master/src/offenewahlen_nrw17/settings.py#L117.  AFAICS, the `$DATABASE_URL` must be set prior to the migrate command.  What is the recommended way to set up the local database?

**Comment by skasberger** [comment]
on my ubuntu 16.04 it works like this: instead of DATABASENAME fill in your self-created postgresql database.

```
export DATABASE_URL=postgres:///DATABASENAME
```

but i will fix this in the documentation, cause we already had this issue several times.

**Comment by fleimgruber** [comment]
Yep, that works, so resolved.  Leaving this issue open in case you want it as reminder for addition to documentation.  Feel free to close otherwise.

**Comment by skasberger** [comment]
The project is closed, but you can find the new one at [owat_api](https://github.com/skasberger/owat_api/wiki/Software-Architecture).
