### ISSUE TITLE
gemeindekennzahlen daten besorgen

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#23]
es braucht für die kontrolle der eingangsdaten vom bmi vermutlich eine datei mit der gemeindekennzahl, dem namen der gemeinde und vielleicht anderen daten, um einen Join machen zu können.

**Comment by frocentus** [comment]
Liste der Gemeinden (inkl. ihrer GKZ, Gemeindecode und Bezeichnung und Art [Marktgemeinde, Statuarstadt, Stadtgemeinde] ) gibt's bei der Statistik Austria (
unter https://www.statistik.at/web_de/klassifikationen/regionale_gliederungen/gemeinden/index.html ) als CSV http://www.statistik.at/verzeichnis/reglisten/gemliste_knz.csv

Der Gemeindecode ist nur in Wien relevant zur Unterscheidung der 23 Bezirke.

Bei den Wahlen ist die spatial_id (zumindest bei der NRW 2013) eine Mischung aus diesen Daten.

Zur Kodierung der Gemeinde (unterste Ebene) verwendet das BMI offensichtlich den Gemeindecode. 

Eine Ebene darüber sind dann die Bezirke (103..)

Eine weitere Ebene sind dann die Wahlkreise, für die sie dann nochmals eigene Codes haben (wie 1A000 für 'Burgenland Nord' und analog dazu 1A099 für 'Wahlkarten - Burgenland Nord').

Zusätzlich gibt es für jeden Bezirk | Wahlreis | Bundesland noch einen Eintrag mit einer '99' als letzte zwei Stellen für die Anzahl der abgegebenen Wahlkarten in diesen Bezirk | Wahlkreis | Bundesland.

Für das Burgenland sieht dann der Aufbau so aus

spatial_id | Bezeichnung 
-----------|--------------
G10000    | Burgenland
G10099    | Wahlkarten - Burgenland
G10100    | Eisenstadt (Stadt)
G10101    | Eisenstadt
G10199    | Wahlkarten - Eisenstadt (Stadt)
G10200    | Rust (Stadt)
G10201    | Rust
G10299    | Wahlkarten - Rust (Stadt)
G10300    | Eisenstadt - Umgebung
G10301    | Breitenbrunn am Neusiedler See
G.........       | ......
G10399    | Wahlkarten - Eisenstadt Umgebung
G104....     | ......
G.........       | ......
G109....     | ......
G10A000  | Burgenland Nord
G10A099  | Wahlkarten - Burgenland Nord
G10B000  | Burgenland Süd
G10B099  | Wahlkarten - Burgenland Süd

**Comment by frocentus** [comment]
mir ist da noch was eingefallen. 2015 gab es in der Steiermark ja jede menge Zusammenlegungen von gemeinden, d.h. es wird nicht (ohne aufwändigen Mechanismus) möglich sein alle steiermärkischen Gemeinden historisch zu vergleichen, da es hier Veränderungen in den Gemeindekennziffern gab, soweit ich mich erinnern kann, bekamen fusionierte Gemeinden neue GKZs zugeweisen.

EDIT: ja, dem ist so - bei allen Fusionierungen wurde immer eine neue GKZ erzeugt. Trifft dann leider auch große Gemeinde wie Bruck, Kapfenberg, Mürzzuschlag, Deutschlandsberg (G60302 <=> G60344), Leibnitz, Murau, Knittelfeld, Feldbach.

**Comment by ginseng666** [comment]
stimmt, es gab auch in oö zwei fusionen und wien umgebung ist seit anfang 2017 geschichte, hier gibts auch neue gkzs. 

zur steiermark hab ich irgendwo eine datei mit alt/neu, um das vergleichbar zu machen - ganz perfekt wird es aber nicht, da einige wenige gemeinden geteilt wurden, das lässt sich nicht genau umrechnen.

**Comment by skasberger** [comment]
https://github.com/OKFNat/offenewahlen-nrw17/commit/dd2a8f8d4b209eeeecdf1403daf1874659ad41ca
