### ISSUE TITLE
geometrien klären

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#24]
um die ergebnisse visuell darstellen zu können, wird eine räumliche geometrie benötigt (geojson, shape). Diese muss die Gemeindekennzahl als Attribut beinhalten und bereits in der benötigten Projektion vorliegen.

**Comment by frocentus** [comment]
Dazu habe ich mir gestern was angesehen:

 Das BEV bietet bei seinen "kostenlosen Produkten" den Download für die Verwaltungsgrenzen an: http://www.bev.gv.at/portal/page?_pageid=713,2601287&_dad=portal&_schema=PORTAL

Aus diesen Downloads (DBF, PRJ, SHP, SHX) kann man mittels eines Online-Converters ( https://mygeodata.cloud/converter/shp-to-geojson ) GeoJSON - Strukturen erzeugen.

In diesen Datensatz sind dann die Umrisse der Gemeinde drinnen, Bezeichnungen, GKZ, Bezirksinfos usw.

Ich hab mir bis jetzt nur das File für Burgenland angesehen, da sind die Gemeinden drinnen, ich weiß nicht ob es da auch in anderen Files übergeordnete Strukturen (bzw. Umriss Bezirk, Umriss Land) gibt.

**Comment by ginseng666** [comment]
Bundesländer, Bezirke und Gemeinden aktuell siehe auch https://github.com/ginseng666/GeoJSON-TopoJSON-Austria, also geojson/topojson in unterschiedlicher Vereinfachung; enthält die GKZ und den Namen

**Comment by ximex** [comment]
Ich würde diesen Datensatz vom BEV empfehlen. Dort sind sogar Katastralgemeinden drinnen etc: https://www.data.gv.at/katalog/dataset/51bdc6dc-25ae-41de-b8f3-938f9056af62
Oder man holt sich die Daten aus der OpenStreetMap

**Comment by skasberger** [comment]
done. https://github.com/OKFNat/offenewahlen-nrw17/commit/f1230a33d7977490c05cb8c21eebff61c92faed7
