### ISSUE TITLE
Was könnte am Wahlabend alles passieren?

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#29]
Brainstormen, welche Ereignisse am Wahlabend passieren können. Dies ist nützlicher Input, um dies vielleicht in die Visualisierungen einfliessen zu lassen.

**Ideen**
* Twitter Storm
* Ergebnisse werden nicht akzeptiert: Verschwörungs-Theorien
* Einflussnahme von Aussen: z. B. Russland

**Comment by ginseng666** [comment]
ad verschwörungstheorien, das kann auch die darstellung betreffen: imho sehr wichtig ist genau auszuschildern, was die daten sind/zeigen und was nicht - alle medien werden am wahlabend hochrechnungen verwenden, die vom running total des bmi etwas bis sehr abweichen werden (je nach zeit), da gilt es zu vermeiden, dass dann die abweichungen zu einem vermeintlichen thema werden (siehe bp-wahl mit wahlkarten)
