### ISSUE TITLE
darstellung im edge

### ISSUE THREAD

**Issue by frocentus** [Forum-Informationsfreiheit/offenewahlen_api#33]
Der Edge-Browser kommt nicht zurecht (ich vermute mit dem grid, obwohl er es eigentlich unterstützen sollte)

![pasted image at 2017_07_23 09_42 pm](https://user-images.githubusercontent.com/3882400/28502366-f48ffc6c-6ff0-11e7-8da4-bf020cd62e23.png)

Im IE sieht es ganz ähnlich aus.

EDIT sagt:
https://stackoverflow.com/questions/44329182/css-grid-layout-content-collapsing-on-microsoft-edge

Sieht so aus, als ob IE nur einen alten Standard der CSS-Grid-Implementation unterstützt. In der Antwort auf Stackoverflow steht ein Link zu mehr Details.

**Comment by frocentus** [comment]
also folgendes hab ich rausgefunden, damit es im edge halbwegs ausschaut (CSS-grid ist dort geprefixed und nicht auf den aktuellen Status wie andere Browser)

das div mit der class "countdown-timer" braucht:

- "display: -ms-grid;"
- "-ms-grid-columns: ( 200px ) [4];"
- "-ms-grid-rows: min-content;"

das erste div mit der "class" item braucht einen inline-style (oder halt über eine id)

- "ms-grid-column: 1;"

das erste div mit der class "item" braucht einen inline-style (oder halt über eine id)

- "ms-grid-column: 2;"

analog natürlich für item 3 und 4 natürlich auch.

**Comment by tobias47n9e** [comment]
Edge hat einen Markanteil von 1% und Version 16 hat Support für Grid angekündigt. Bin mir nicht sicher ob sich der Aufwand lohnt. Aber PRs sind natürlich willkommen.

**Comment by skasberger** [comment]
@frocentus sieht es jetzt besser aus mit edge? hab auf bootstrap fürs layouting umgestellt.

**Comment by frocentus** [comment]
Viel besser:

![image](https://user-images.githubusercontent.com/3882400/28536396-c099e550-70a7-11e7-89ea-94802f3e407c.png)

**Comment by skasberger** [comment]
fixed with https://github.com/OKFNat/offenewahlen-nrw17/commit/b50f448dd6b2e8efa223f3a9b82aa6a20079f998
