### ISSUE TITLE
Download results from web/API

### ISSUE THREAD

**Issue by chreman** [Forum-Informationsfreiheit/offenewahlen_api#4]
* pre-scheduled via cron/config/hardcoded
* via manueller aufforderung (backend-login, frontend url-call)

**Comment by chreman** [comment]
Ich würde eine config.json anlegen, in der sowas wie ein "update-interval" festgelegt wird, das dann vom preprocessing prozess eingelesen wird.
Manuelle Aufforderung durch frontend calls würde ich nicht machen. unnötiges feature im interface, die daten kommen dadurch eh nicht schneller, erzeugt nur falsche erwartungen. refresh im frontend geht maximal bis zur db.
backend-login sehe ich gerade keinen speziellen nutzen? comment?

**Comment by skasberger** [comment]
das xml würde ich jedes mal speichern und versionieren (diff oder mittels filenam). geht speichern bei heroku überhaupt?

**Comment by tobias47n9e** [comment]
Alternativ könnte man auch den inhalt von jeder XML datei in die Datenbank schreiben. Als XML Spalte oder einfach als Text.

https%3A%2F%2Fwww.postgresql.org%2Fdocs%2F9.6%2Fstatic%2Fdatatype-xml.html

**Comment by chreman** [comment]
persistenz gibt es innerhalb eines dynos nicht, die werden 1x alle 24h neu gestartet. persistenz und korrektheit der daten muss daher über das DB-schema und die app-logik hergestellt werden

**Comment by frocentus** [comment]
gibt es beim Import auch "Summendokumente", dh. Summen für einen Bezirk? Wenn nein, sollten die beim Import bzw. nach dem Import gleich generiert und in der DB gespeichert werden, damit dann der Zugriff aus dem Frontend schneller ist.

Anbieten zur Summierung würde sich die Gemeindekennzahl 'GKZ', die ja hierarchisch aufgebaut ist:
1* = BGLD
103* = Bezirk Eisenstadt-Umgebung

Wir haben das bei uns in der DB auch so abgelegt, dass - sobald ein neues Ergebnis einer Gemeinde reinkommt, diese "Summendokumente" (liegen bei uns in einer IBM Domino DB) generiert bzw. aktualisiert werden.

Zusätzlich braucht man diese Summendokument auch noch zur Berechnung der Mandatsverteilung.

EDIT: Gerade gesehen, wenn man die NRW2013 ansieht, gibt es dort diese Summendokumente (z.b. spatial_id "G10300")

**Comment by skasberger** [comment]
würde das scheduling auch in der config.json machen. hab da auch die xml_url sowie die kürzel der parteien drinnen. 

wegen summen: vermutlich nicht. war zumindest in der vergangenheit so. wir sind aber an sich gut damit aufgehoben, uns nicht auf die korrektheit der eingangsdaten zu verlassen und diese möglichst zu testen.

das mit der GKZ ist eine gute Idee, dazu müssen wir uns aber um eine korrekte Datengrundlage kümmern. werd dazu mal ein issue aufmachen.

**Comment by ginseng666** [comment]
Summen wären sehr gut, ich glaub auch nicht, dass das BMI unvollständige Summen zb für Bezirke mitschickt.

Ebenfalls gut wäre, wenn pro ausgezählter Gemeinde gleich ein Feld "winner" o.ä. mit einer (auch festzulegenden) Partei-ID ausgegeben wird, das erleichtert das Karten-Einfärben sehr.

**Comment by skasberger** [comment]
hab jetzt mal schnell das speichern des xml mitsamt metadaten implementiert.

**Comment by skasberger** [comment]
es wird keine xml geben, nur txt, csv und json,

**Comment by skasberger** [comment]
done.
