### ISSUE TITLE
Sitemap erstellen

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#40]
es braucht für den launch eine sitemap.xml, damit google etc sauber indezieren können.

* soll via function-call erstellt werden können
* soll beim launch automatisch erstellt werden
* wie einbinden in website navigation?

**Comment by skasberger** [comment]
https://docs.djangoproject.com/en/1.11/ref/contrib/sitemaps/

**Comment by tobias47n9e** [comment]
And href-lang: https://support.google.com/webmasters/answer/189077?hl=de
