### ISSUE TITLE
Datenauslieferung: Datengröße minimieren

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#41]
die daten die der client zum darstellen der visualisierung benötigt so weit wie möglich reduzieren bzw. zeitlich verteilen. Smartphones mit 3G Anschluss beachten.

option 1: erste visualisierung bei responsive benötigt nur kleine datenmenge. während diese betrachtet wird, kann restlicher datensatz nachgeladen werden.

option 2: lade screen solange bis daten komplett sind

option 3: auflösung (zeitliche oder räumliche) bei kleinen screens reduzieren. zB bezirks oder landesergebnisse anstatt gemeinde-ebene.

**Comment by ginseng666** [comment]
option 1 oder 2 sind beide denke ich gut machbar. da der flaschenhals die gemeindeergebnisse sind, könnte man zunächst nur die balken zeigen und dann erst die karte.

option 3 erscheint mir weniger ideal, weil auf den ebenen vollständige ergebnisse erst später kommen und auch die idee, den auszählungsgrad zu zeigen, leidet.

die datenmenge ist glaub ich überschaubar: das gesamte ergebnis-csv der nrw2013 mit allen gemeinden hat bei mir 140kb, mit gesamtdaten und vergleich wirds größer, geht aber nicht durch die decke.

**Comment by skasberger** [comment]
gesamtergebnis zuerst aussenden und dann die gemeindeergebnisse nachladen lassen.

**Comment by skasberger** [comment]
daten bei aussendung komprimieren. sollte an sich aber von django eh schon so gemacht werden.

**Comment by ginseng666** [comment]
ich schreibs hier nochmals rein, ist json in stein gemeißelt? wenns nur um die dateigröße beim download geht, ein csv mit allen ergebnissen inklusive gemeindenamen kommt irgendwo rund auf 200kb.

**Comment by skasberger** [comment]
ich bin an sich schon für JSON, aber in Stein gemeißelt ist das nicht. Die Sache ist ja, dass die Ergebnisse alleine auch nicht die gesamte Übertragung ausmachen, sondern auch die Geometrien, Infos zu Parteien, zur Wahl, Gemeinden, Bezirke etc. Werds mal durchtesten, wieviel man sich ersparen würde.
