### ISSUE TITLE
Einheitliche Farbpalette für die Parteien

### ISSUE THREAD

**Issue by ginseng666** [Forum-Informationsfreiheit/offenewahlen_api#43]
spätestens wenn alle parteien feststehen - eine einheitliche farbpalette definieren (die idealerweise auch noch hübsch ist)

**Comment by ximex** [comment]
Diese sollte man auch gleich in der `parties.json` Datei definieren

**Comment by skasberger** [comment]
es gibt keine offiziellen farbcodes, daher hängen die gewählten farben mehr von gestalterischen bzw. kognitiven aspekten ab. da hat jede/r ein bisschen seine eigene philosophie. daher sollte die entscheidung bei der design person belassen werden, also client-seitigs. bei uns wird das dann vermutlich auch in einer json hard-gecoded, die an den server ausgeliefert werden soll. Hintergrund: Die app soll in Zukunft Richtung Open Data API weiter entwickelt werden, daher macht die Trennung zwischen Datenbank und Client noch mehr sinn. 

Überlegen müssen wir uns aber auf jeden Fall eine, ist dann halt nur für uns und hat keine universelle Gültigkeit.
