### ISSUE TITLE
Partei Listen

### ISSUE THREAD

**Issue by ximex** [Forum-Informationsfreiheit/offenewahlen_api#46]
https://de.wikipedia.org/wiki/Liste_der_politischen_Parteien_in_%C3%96sterreich
http://www.bmi.gv.at/cms/bmi_service/parteienverz/start.aspx

Achtung: Die Nr ist keine fixe Nr. Die ist einfach eine Aufzählung der alphabetisch sortiereten Parteien

**Comment by skasberger** [comment]
Erstellen und verwalten einer Liste mit den benötigten Parteien für die NRW13 und NRW17. 

**Inhalt**
* [x] Wikidata ID der Partei
* [x] Voller Name der Partei
* [x] Kürzel der Partei
* [x] Parteienfamilie auf europäischer Ebene: Historie erhalten.

**Comment by skasberger** [comment]
done. https://github.com/OKFNat/offenewahlen-nrw17/commit/28927918a7ef76588e38c3df243afc3d92ccdf75
