### ISSUE TITLE
Tests: Datenimport

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#52]
Durchführen von Checks zu den Rohdaten mit den postgresql Eintragungen. Ergebnisse der einzelnen Checks in Datenbank abspeichern -> eigene Class dafür erstellen und mit Rawdata verknüpfen.

Entwerfen von TestDatasets (JSON). Mehrere Eintragungen, die immer mehr werden.

**Checks**
* [ ] import base data
* [ ] delete base data
* [ ] delete result data
* [ ] check integrity of results data itself
  * [ ] Summe der Stimmen von aller Parteien == Anzahl valider Stimmen
  * [ ] valide Stimmen + invalide Stimmen == abgegebene Stimmen
  * [ ] Zahl Wahlberechtigter >= abgegebene Stimmen
  * [ ] kommt ein Wert im erwarteten Daten.Typ daher
  * [ ] fehlen eines wertes einer partei
  * [ ] none wert bei partei
  * [ ] timestamp falsch formatiert
  * [ ] eine partei fehlt
  * [ ] mapping key nicht vorhanden
  * [ ] encoding aller files testen ob uft-8
* [ ] check import of results data
  * [ ] from URL
  * [ ] from local file
  * [ ] with mapping
  * [ ] without mapping
  * [ ] check hash
  * [ ] Zeitstempel der Datei-Erstellung zwischen Schliessung des ersten Wahllokals und aktuellem Zeitpunkt
  * [ ] null wert bei partei
  * [ ] alter eintrag zu einer GKZ wird nicht gelöscht oder überschrieben, sondern es kommt ein neuer dazu.
  * [ ] Werden Reihen in den jeweiligen Tabellen angelegt, wenn diese nicht vorhanden?
  * [ ] Werden Reihen in den jeweiligen Tabellen aktualisiert, wenn sich die Werte ändern?
  * [ ] Anzahl Einträge in den Tabellen gleich dem Count der Input-Daten?
  * [ ] wenn keine Änderung von file zu file vorgenommen werden: wird der import ausgeführt?
  * [ ] Gemeindekennzahl nicht existent
  * [ ] Wahlkarte als GKZ
  * [ ] Wahlkarte nicht existent
  * [ ] Gesamtergebnis als GKZ
  * [ ] Regionalwahlkreis als GKZ
  * [ ] Regionalwahlkreis nicht existent
  * [ ] zeitstempel sind nicht chronologisch sortiert, sondern es springt ein wert retour
  * [ ] ein key ist enthalten, der nicht im mapping angegeben wird
  * [ ] bundeslandergebnis als GKZ
  * [ ] bundesland nicht existent
  * [ ] mapping datei nicht vorhanden
  * [ ] import von spatial_id gegen liste mit allen GKZs testen
  * [ ] Testen ob in richtige Datenbank geschrieben wurde.
* [ ] Fehler in Datei
* [ ] finales Ergebnis
  * [ ] Gemeinde-Ergebnis fehlt
  * [ ] Gemeinde-Ergebnis doppelt
  * [ ] Wahlkarten-Ergebnis fehlt
  * [ ] Wahlkarten-Ergebnis doppelt
  * [ ] RWK-Ergebnis fehlt
  * [ ] RWK-Ergebnis doppelt

**Comment by tobias47n9e** [comment]
Einige Tests laufen jetzt durch. Da gibt es aber noch viel zu tun. Alle diese Sonderfälle abzudecken wird in der verbliebenen Zeit sich schwierig.
