### ISSUE TITLE
Ablauf des Umschaltens ausarbeiten

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#69]
Umschalten von Counter auf Computing und von Computing auf Visualisierung.

Ablauf dann testen.

**Comment by tobias47n9e** [comment]
Wenn der Counter abläuft könnte das JS in einem regelmäßigen Interval den Server anpingen. Wenn wir die Daten importiert haben, dass müsste die URL sowas wie "Fertig" zurückschicken und das JS lädt die Seite neu.

Eleganter wäre das mit Websockets, aber das geht sich vielleicht zeitmäßig nicht aus.
