### ISSUE TITLE
Was soll mit der Visualisierung nach dem finalen Ergebnis passieren?

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#72]
Was soll mit der Domain, der Visualisierung usw. nach dem verkünden des finalen Ergebnisses passieren?

**Comment by 5k9m** [comment]
Wie ist die Frage genau gemeint?

Persönlich sehe ich das Projekt als ersten Schritt generell Wahl-Daten auch in einem historischen Kontext zu erkunden. Auf orf.at werden die Daten runter genommen, die meisten anderen News-Seiten geben keine ordentliche historische Übersicht. Auch von Seiten des Innenministeriums fehlt imo eine richtige Aufarbeitung. 

Daher finde ich, dass das Projekt #nrw17 durchaus weiterverwendet werden sollte. Oder habe ich die Frage falsch verstanden?

**Comment by skasberger** [comment]
:) jap, da hab ich nicht genau genug angegeben, was ich meine. Ich meinte, wie man vom Schritt, dass die Gemeindeergebnisse da sind, weiter macht. Dann kommen noch die Wahlkarten und am Ende ein finales Ergebnis.

Zu deinen Punkten: Die Domain bleibt auf jeden Fall bestehen. Die Django-App soll aber weiter wachsen und Schritt für Schritt mehr Funktionalitäten und Daten beinhalten. Idee ist, dass es DIE Platform für Offene Wahldaten in AT sein soll (liegt ja an sich schon im Namen). Daher glaub ich, dass wir da ziemlich auf gleicher Linie sind. Seh hier vor allem den Ausbau der API zentral mitsamt Datenstandard.
