### ISSUE TITLE
Virtualenv auf python3 einstellen

### ISSUE THREAD

**Issue by klmmmv** [Forum-Informationsfreiheit/offenewahlen_api#74]
Wenn man der Installationsanleitung folgt, bringt man die app nicht zum laufen, da in der virtuellen pythonumgebung `python` auf `python2.7` linked (unter Linux).

Lösung:
~~~bash
cd /project/root/venv/bin/
ln -sfn python3 python
~~~

Um ehrlich zu sein hab ich keine Ahnung wie das bei Windows gemacht wird.

**Comment by skasberger** [comment]
@chreman wenn ich das richtig verstehe, hat das nix mit dem venv zu tun, sondern mit der lokalen installation von python. also dass python2 noch als standard für python gebinded ist. 

wie lösen? 
* hinweisen auf korrekte installation von python3 bei install?
* die commands von `python` auf `python3` abändern, damit die aktuellst intalliserte pythn 3 version ausgeführt wird?

**Comment by klmmmv** [comment]
Bei mir war die Situation wie folgt:
Ich habe python2 und python3 installiert. Aber python3 ist in meiner normalen Umgebung aktiv. Wenn ich dann ins `venv` wechsle ist python2 aktiv. Also virtualvenv erstellt ja den `venv/bin/` folder und darin den Link von `python` -> `python2`.
Hab halt mit virtualenv keine Erfahrung, aber so wars bei mir.

**Comment by chreman** [comment]
in diesem fall klingt das so als wäre die python version des venv auf 2 konfiguriert. wenn du z.B. anaconda nutzt, kannst du beim erstellen des env die python version mitgeben https://conda.io/docs/py2or3.html

**Comment by skasberger** [comment]
Danke @klmmmv. Hab jetzt drei einfache Wege das Problem zu Lösen in die README.md gegeben. Geht eigentlich immer nur um ein Linking-Problem (gibt bei mir einen python und einen python3 link in venv/bin/) 

https://github.com/OKFNat/offenewahlen-nrw17/commit/711b36ff8beb3d5ed8708dc50d6fbc08fc882daa
