### ISSUE TITLE
check memory limiations of heroku postgres db

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#81]
check memory limiations of heroku in regards of postgres db cause of raw_data storage over longer term.

**Comment by chreman** [comment]
there's no "memory limitation" in the sense of physical space. limitations on heroku are 'row limitations', enforced according to the chosen plan https://devcenter.heroku.com/articles/heroku-postgres-plans

**Comment by skasberger** [comment]
and if we hit the limit: store everything in one big json file in one row.
