### ISSUE TITLE
Installation Applikation auf Windows (10)

### ISSUE THREAD

**Issue by frocentus** [Forum-Informationsfreiheit/offenewahlen_api#86]
Folgende Dinge habe ich 'anders' machen müssen, wie in der [Anleitung](https://github.com/OKFNat/offenewahlen-nrw17#install) beschrieben um zu einer lauffähigen, lokalen Applikation zu kommen:

- Bei Punkt 3:
Den Befehl `source` gibt es unter Windows nicht, als Powershell-User habe ich das bereitgestellte Script verwendet: '. .\venv\Scripts\activate.ps1', damit wechselt man in das VENV

- Bei Punkt 4:
Ich habe die leere Datenbank zuerst im Postgres angelegt, und die `settings.py` wie folgt adaptiert:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME'),
        'USER': os.environ.get('DATABASE_USER'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
        'HOST': os.environ.get('DATABASE_HOST'),
        'PORT': os.environ.get('DATABASE_PORT')
    }
}
```

Danach lief das Migrationsscript fehlerfrei durch, vorher hatte er sich beschwert, dass die Attribute (ENGINE, NAME, usw.) gefehlt haben. Die Variablen habe ich in der Powershell gesetzt:
```
New-Item -Path env:DATABASE_NAME -Value nrw17
New-Item -Path env:DATABASE_USER -Value xxxxxxx
New-Item -Path env:DATABASE_PASSWORD -Value xxxxxxx
New-Item -Path env:DATABASE_HOST -Value localhost
New-Item -Path env:DATABASE_PORT -Value 5432
```

**Comment by 5k9m** [comment]
@skasberger Wäre es nicht "einfacher" ein generelles Dockerfile aufzusetzen als unterschiedliche Anleitungen zu schreiben? So würde die Installation vereinheitlicht werden können und auch manche Bauchschmerzen in der Entwicklung wegfallen.

**Comment by skasberger** [comment]
@5k9m das ist ne gute Idee. Werd dazu ein Issue für die nächste Version nach der Wahl anlegen, damit wir das dann mal besprechen können. https://github.com/OKFNat/offenewahlen-nrw17/issues/95

**Comment by skasberger** [comment]
@frocentus geht es jetzt schon bei dir?

**Comment by frocentus** [comment]
Leider nicht, durch die neue requirements.txt kann ich unter Windows 10 nicht mehr alle Abhängigkeiten kompilieren, z.B. Memcached geht nicht:

`  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DUSE_ZLIB -Ic:\python36\include -Ic:\python36\include "-IC:\Progra
m Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\incl
ude\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/_pylibmcmodule.c /Fobuild\temp.win32-3.
6\Release\src/_pylibmcmodule.obj -fno-strict-aliasing -std=c99
  cl : Command line warning D9002 : ignoring unknown option '-fno-strict-aliasing'
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  _pylibmcmodule.c
  c:\users\harald\appdata\local\temp\pip-build-cmbq_rre\pylibmc\src\_pylibmcmodule.h(42): fatal error C1083: Cannot open include file: 'libmemcached/memcached.h': No such
file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2`

Beim Aufruf von 'manage.py migrate' setzt es mittlerweile folgenden Fehler:

`ModuleNotFoundError: No module named 'rest_framework'`

Danach machte ich ein `pip3 install djangorestframework`, dann lief zumindest das migrate-script wieder, owohl er beim vorigen install das djangorestframework installiert hatte:
`Collecting djangorestframework==3.6.4 (from -r .\requirements.txt (line 7))
  Downloading djangorestframework-3.6.4-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 511kB/s
`

**Comment by frocentus** [comment]
Damit bei mir die Datenbank ordentlich erstellt wurde, musst ich folgende Commandos ausführen (Danke Tobias)


- `python .\src\manage.py makemigrations viz`
- `python .\src\manage.py migrate`

Dann ging auch die WebApp endlich :)

**Comment by tobias47n9e** [comment]
Hab jetzt die Migrationen im Git hinzugefügt: https://github.com/OKFNat/offenewahlen-nrw17/tree/master/src/viz/migrations

Somit sollte `python .\src\manage.py migrate` ausreichen (Bis natürlich der nächste das Schema ändert und die Migration nicht comitted)
