### ISSUE TITLE
Infos zu Ablauf der Wahl einholen 

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#90]
Wie kommen die Daten von 17h am 15. Oktober bis zur amtlichen Verkündung ein paar Tage später daher? Immer selbes File, immer selbe Struktur, immer selber Inhalt? 

Wenn sich was ändert, was genau und wann?

**Comment by skasberger** [comment]
@ginseng666 hast du da irgendwelche Erfahrungswerte?

**Comment by ginseng666** [comment]
imho gibts nach dem wahlsonntag nur wieder ein update, wenn alle stimmen ausgezählt sind - kann aber dieses mal durchaus anders sein (bei der bp-wahl hat salzburg von sich aus vorab ausgezählte bezirke online gestellt, das bmi hat das nicht sehr goutiert)

**Comment by skasberger** [comment]
also die ergebnisse kommen einfach unten angereiht mit einer gemeindekennzahl daher, welche für eine Briefwahl steht, right?

was würdest du denn sagen, das wir machen? wien differenzieren? ich find, wenns geht, die möglichst kleinste räumliche einheit nehmen.

**Comment by ginseng666** [comment]
würde ich bei der karte nicht - entweder alles gemeinden oder alles bezirke, bei den bezirken wären dann ja wieder die wahlkarten dabei.
