### ISSUE TITLE
Dyno-Pläne umschalten

### ISSUE THREAD

**Issue by chreman** [Forum-Informationsfreiheit/offenewahlen_api#94]
Kostenlose Versionen sind stark performance limitiert.

Rechtzeitig (evtl. mit Test am Vortag) die Dyno-Pläne von den kostenlosen Versionen auf höhere Versionen umschalten. Nach dem großen Ansturm kann wieder runtergestuft werden. (Abrechnung geschieht nach zeitlichen Anteilen)

**Comment by chreman** [comment]
auf staging wurde temporär der plan für postgresql erhöht

https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases#upgrade-with-pg-copy

* provision new db: `heroku addons:create heroku-postgresql:hobby-basic -a APPNAME`
* wait until ready: `heroku pg:wait -a APPNAME`
* activate maintenance to prevent further writes and data loss: `heroku maintenance:on -a APPNAME`
* copy data from old to new: `heroku pg:copy DATABASE_URL HEROKU_POSTGRESQL_ORANGE_URL -a APPNAME` (or some other `COLOR`)
* promote new database to active db: `heroku pg:promote HEROKU_POSTGRESQL_PINK -a APPNAME`
* switch maintenance off: `heroku maintenance:off -a APPNAME`

**Comment by skasberger** [comment]
@chreman kannst du die Deployment Sachen auch wo dokumentieren, so dass das Wissen weiter gegegben wird? Wenn da einiges nicht public sein darf, am besten in einem Google Doc. Sonst Wiki bitte. oder in einem privaten gist.
