### ISSUE TITLE
Hack-Session im September organisieren

### ISSUE THREAD

**Issue by skasberger** [Forum-Informationsfreiheit/offenewahlen_api#97]
* Doodle aussenden
* Ort klären
* TeilnehmerInnen erinnern

**Comment by klmmmv** [comment]
Bitte mal die Termine anschauen und mir sagen, ob ihr lieber unter Tags das machen wollt, oder ob gegen Abend hin euch eh passt.
https://beta.doodle.com/poll/mf68stbvi68zb86n

**Comment by skasberger** [comment]
ist eigentlich soweit abgeschlosse, oder @klmmmv ?
